package main

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/url"
	"strconv"
	"strings"
	"time"
)

func parseSS(raw string) (map[string]interface{}, error) {
	rest:=strings.TrimPrefix(raw,"ss://");frag:="";if i:=strings.Index(rest,"#");i>=0{frag,_=url.QueryUnescape(rest[i+1:]);rest=rest[:i]};var userinfo,hostport string;if at:=strings.LastIndex(rest,"@");at>=0{userinfo,hostport=rest[:at],rest[at+1:];if dec:=decodeB64String(userinfo);dec!=""{userinfo=dec}}else{dec:=decodeB64String(rest);if dec==""{return nil,errors.New("invalid ss base64")};at:=strings.LastIndex(dec,"@");if at<0{return nil,errors.New("invalid ss payload")};userinfo,hostport=dec[:at],dec[at+1:]};c:=strings.Index(userinfo,":");if c<1{return nil,errors.New("invalid ss method/password")};method,password:=userinfo[:c],userinfo[c+1:];host,portStr,err:=net.SplitHostPort(hostport);if err!=nil{return nil,err};port,err:=strconv.Atoi(portStr);if err!=nil{return nil,err};if frag==""{frag=host};return map[string]interface{}{"name":frag,"type":"ss","server":host,"port":port,"cipher":method,"password":password,"udp":true},nil
}
func parseSocks(raw string)(map[string]interface{},error){u,err:=url.Parse(raw);if err!=nil{return nil,err};host,port,err:=hostPort(u);if err!=nil{return nil,err};p:=map[string]interface{}{"name":nodeName(u,host),"type":"socks5","server":host,"port":port,"udp":true};if u.User!=nil{if user:=u.User.Username();user!=""{p["username"]=user};if pw,ok:=u.User.Password();ok{p["password"]=pw}};return p,nil}
func applyTransport(p map[string]interface{},q url.Values){network:=strings.ToLower(firstNonEmpty(q.Get("type"),q.Get("network")));switch network{case "ws":p["network"]="ws";opts:=map[string]interface{}{};if path:=q.Get("path");path!=""{opts["path"]=path};if h:=q.Get("host");h!=""{opts["headers"]=map[string]interface{}{"Host":h}};if ed:=q.Get("ed");ed!=""{opts["max-early-data"]=toIntOrString(ed)};p["ws-opts"]=opts;case "grpc":p["network"]="grpc";service:=firstNonEmpty(q.Get("serviceName"),q.Get("service-name"));p["grpc-opts"]=map[string]interface{}{"grpc-service-name":service};case "http","h2":p["network"]="http";opts:=map[string]interface{}{};if path:=q.Get("path");path!=""{opts["path"]=[]string{path}};if h:=q.Get("host");h!=""{opts["headers"]=map[string]interface{}{"Host":[]string{h}}};p["http-opts"]=opts}}
func rebuildConfig(dir string,st State)error{core:=normalizeCore(st.Core);if core==""{core="sing-box"};switch core{case "sing-box":return rebuildSingBoxConfig(dir,st);case "xray","v2ray":return rebuildXrayConfig(dir,st,core);case "mihomo":return rebuildMihomoConfig(dir,st);default:return fmt.Errorf("unsupported core: %s",st.Core)}}
func normalizeCore(core string)string{core=strings.ToLower(strings.TrimSpace(core));switch core{case "singbox","sing_box","sing-box":return "sing-box";case "xray":return "xray";case "v2ray","v2fly":return "v2ray";case "mihomo","clash","clash-meta":return "mihomo";default:return ""}}
func splitNonEmpty(s,sep string)[]string{var out []string;for _,p:=range strings.Split(s,sep){p=strings.TrimSpace(p);if p!=""{out=append(out,p)}};return out}
func nodeRefLocal(id string)string{return "local:"+id};func nodeRefSub(subID,nodeID string)string{return "sub:"+subID+":"+nodeID};func chainRef(id string)string{return "chain:"+id}
func resolveNodeRef(st State,ref string)(ServerEntry,bool){if strings.HasPrefix(ref,"local:"){id:=strings.TrimPrefix(ref,"local:");for _,n:=range st.Servers{if n.ID==id{return n,true}}};if strings.HasPrefix(ref,"sub:"){rest:=strings.TrimPrefix(ref,"sub:");parts:=strings.SplitN(rest,":",2);if len(parts)==2{for _,sub:=range st.Subscriptions{if sub.ID!=parts[0]{continue};for _,n:=range sub.Nodes{if n.ID==parts[1]{return n,true}}}}};return ServerEntry{},false}
func removeChain(chains []ChainEntry,id string)[]ChainEntry{out:=chains[:0];for _,c:=range chains{if c.ID!=id{out=append(out,c)}};return out}
func measureNodeLatency(ref string,n ServerEntry)LatencyResult{host,port,err:=nodeEndpoint(n);if err!=nil{return LatencyResult{Ref:ref,Error:err.Error()}};ctx,cancel:=context.WithTimeout(context.Background(),2500*time.Millisecond);defer cancel();start:=time.Now();d:=net.Dialer{Timeout:2300*time.Millisecond};conn,err:=d.DialContext(ctx,"tcp",net.JoinHostPort(host,strconv.Itoa(port)));if err!=nil{return LatencyResult{Ref:ref,Error:"timeout"}};_=conn.Close();return LatencyResult{Ref:ref,LatencyMS:time.Since(start).Milliseconds()}}
func nodeEndpoint(n ServerEntry)(string,int,error){if n.Proxy!=nil{h:=strings.TrimSpace(stringValue(n.Proxy["server"]));p:=intValue(n.Proxy["port"]);if h!=""&&p>0{return h,p,nil}};if n.RawKind=="sing-box"&&n.Raw!=nil{h:=strings.TrimSpace(stringValue(n.Raw["server"]));p:=intValue(n.Raw["server_port"]);if h!=""&&p>0{return h,p,nil}};if n.RawKind=="xray"&&n.Raw!=nil{if settings,ok:=n.Raw["settings"].(map[string]interface{});ok{for _,key:=range []string{"vnext","servers"}{if arr,ok:=settings[key].([]interface{});ok&&len(arr)>0{if m,ok:=arr[0].(map[string]interface{});ok{h:=firstNonEmpty(stringValue(m["address"]),stringValue(m["server"]));p:=intValue(m["port"]);if h!=""&&p>0{return h,p,nil}}}}}};return "",0,errors.New("server address is unavailable")}
func allNodes(st State)[]struct{Ref string;Node ServerEntry;Group string}{var out []struct{Ref string;Node ServerEntry;Group string};for _,n:=range st.Servers{out=append(out,struct{Ref string;Node ServerEntry;Group string}{nodeRefLocal(n.ID),n,"Local"})};for _,sub:=range st.Subscriptions{for _,n:=range sub.Nodes{out=append(out,struct{Ref string;Node ServerEntry;Group string}{nodeRefSub(sub.ID,n.ID),n,sub.Name})}};return out}
func singBoxOutboundFromNode(n ServerEntry,tag string)(map[string]interface{},error){if n.RawKind=="sing-box"&&n.Raw!=nil{m:=cloneMap(n.Raw);m["tag"]=tag;return m,nil};if n.RawKind=="xray"{return nil,errors.New("Xray-only JSON node cannot be used by sing-box")};p:=n.Proxy;if p==nil{return nil,errors.New("empty node")};typ:=strings.ToLower(stringValue(p["type"]));server:=stringValue(p["server"]);port:=intValue(p["port"]);if server==""||port==0{return nil,errors.New("server/port missing")};m:=map[string]interface{}{"type":typ,"tag":tag,"server":server,"server_port":port};switch typ{case "vless":m["uuid"]=stringValue(p["uuid"]);if flow:=stringValue(p["flow"]);flow!=""{m["flow"]=flow};applySingBoxTLS(m,p,true);applySingBoxTransport(m,p);case "vmess":m["uuid"]=stringValue(p["uuid"]);m["security"]="auto";if aid:=intValue(p["alterId"]);aid!=0{m["alter_id"]=aid};applySingBoxTLS(m,p,false);applySingBoxTransport(m,p);case "trojan":m["password"]=stringValue(p["password"]);applySingBoxTLS(m,p,true);applySingBoxTransport(m,p);case "hysteria2":m["password"]=stringValue(p["password"]);applySingBoxTLS(m,p,true);if obfs:=stringValue(p["obfs"]);obfs!=""{ob:=map[string]interface{}{"type":obfs};if pass:=stringValue(p["obfs-password"]);pass!=""{ob["password"]=pass};m["obfs"]=ob};if up:=bandwidthMbps(p["up"]);up>0{m["up_mbps"]=up};if down:=bandwidthMbps(p["down"]);down>0{m["down_mbps"]=down};case "ss":m["type"]="shadowsocks";m["method"]=stringValue(p["cipher"]);m["password"]=stringValue(p["password"]);case "socks5","socks":m["type"]="socks";m["version"]="5";if v:=stringValue(p["username"]);v!=""{m["username"]=v};if v:=stringValue(p["password"]);v!=""{m["password"]=v};default:return nil,fmt.Errorf("protocol %s is not supported by sing-box generator",typ)};return m,nil}
func bandwidthMbps(v interface{})int{s:=strings.ToLower(strings.TrimSpace(stringValue(v)));if s==""{return 0};s=strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(s,"mbps"),"mb"),"m");n,_:=strconv.Atoi(strings.TrimSpace(s));return n}
func applySingBoxTLS(m,p map[string]interface{},force bool){enabled:=force||boolish(p["tls"],false)||stringValue(p["sni"])!=""||stringValue(p["servername"])!="";if !enabled{return};t:=map[string]interface{}{"enabled":true};if sni:=firstNonEmpty(stringValue(p["servername"]),stringValue(p["sni"]));sni!=""{t["server_name"]=sni};if boolish(p["skip-cert-verify"],false){t["insecure"]=true};if fp:=stringValue(p["client-fingerprint"]);fp!=""{t["utls"]=map[string]interface{}{"enabled":true,"fingerprint":fp}};if ro,ok:=p["reality-opts"].(map[string]interface{});ok{r:=map[string]interface{}{"enabled":true};if v:=stringValue(ro["public-key"]);v!=""{r["public_key"]=v};if v:=stringValue(ro["short-id"]);v!=""{r["short_id"]=v};if len(r)>1{t["reality"]=r}};m["tls"]=t}
func applySingBoxTransport(m,p map[string]interface{}){network:=strings.ToLower(stringValue(p["network"]));switch network{case "ws":t:=map[string]interface{}{"type":"ws"};if o,ok:=p["ws-opts"].(map[string]interface{});ok{if v:=o["path"];v!=nil&&stringValue(v)!=""{t["path"]=stringValue(v)};if v:=o["headers"];v!=nil{t["headers"]=v};if v:=o["max-early-data"];v!=nil{t["max_early_data"]=intValue(v)}};m["transport"]=t;case "grpc":t:=map[string]interface{}{"type":"grpc"};if o,ok:=p["grpc-opts"].(map[string]interface{});ok{if v:=stringValue(o["grpc-service-name"]);v!=""{t["service_name"]=v}};m["transport"]=t;case "http","h2":t:=map[string]interface{}{"type":"http"};if o,ok:=p["http-opts"].(map[string]interface{});ok{if v:=o["path"];v!=nil{t["path"]=v};if v:=o["headers"];v!=nil{t["headers"]=v}};m["transport"]=t}}
func uniqueTag(base string,used map[string]int)string{base=strings.TrimSpace(base);if base==""{base="Proxy"};used[base]++;if used[base]==1{return base};return fmt.Sprintf("%s · %d",base,used[base])}
