import { Check, LoaderCircle, ShieldCheck, Smartphone, Wifi, Zap } from 'lucide-react';
import type { BoxConfig, BoxStatus } from '@/types/box';
import type { EasyCore, EasyState } from '@/lib/easy';
import { Card, Toggle } from '@/components/easyMaterial';

type Props={easy:EasyState;config:BoxConfig;status:BoxStatus;busy:string|null;actionLoading:string|null;hasChanges:boolean;onCore:(core:EasyCore)=>Promise<void>;onToggle:(key:string,value:boolean)=>void;onChange:<K extends keyof BoxConfig>(key:K,value:BoxConfig[K])=>void;onAutoStart:(value:boolean)=>Promise<void>;onLog:()=>Promise<void>;onRestart:()=>Promise<void>;onSave:()=>Promise<void>;};

export function TabSettingsEasy({easy,config,status,busy,actionLoading,hasChanges,onCore,onToggle,onChange,onAutoStart,onLog,onRestart,onSave}:Props){
  return <div className="space-y-4 px-4 pb-32 pt-2">
    <Card className="p-4"><h2 className="font-black">Ядро</h2><p className="text-xs opacity-50">sing-box — основной. Остальные нужны только для совместимости.</p><div className="mt-3 grid grid-cols-2 gap-2">{([['sing-box','sing-box','Рекомендуется · JSON · Hysteria2'],['xray','Xray','VLESS · Reality · XHTTP'],['v2ray','V2Ray','V2Fly · VMess/VLESS'],['mihomo','Mihomo','Только legacy Clash/YAML']] as Array<[EasyCore,string,string]>).map(([c,title,desc])=><button disabled={Boolean(busy)} onClick={()=>void onCore(c)} key={c} className={`rounded-[22px] border p-3 text-left ${easy.core===c?'border-[#6750a4] bg-[#e8def8] text-[#1d192b] dark:bg-[#4a4458] dark:text-[#e8def8]':'border-black/10 dark:border-white/10'}`}><div className="text-sm font-black">{title}</div><div className="mt-1 text-[10px] opacity-55">{desc}</div></button>)}</div></Card>
    <Card className="p-4"><h2 className="font-black">Прозрачное туннелирование</h2><div className="mt-3 space-y-3"><label className="block text-xs font-bold opacity-60">Режим</label><select value={Number(config.PROXY_MODE ?? 0)} onChange={e=>onChange('PROXY_MODE',Number(e.target.value))} className="w-full rounded-2xl bg-[#f3edf7] px-4 py-3 text-sm dark:bg-[#2b2930]"><option value={0}>Авто · TPROXY приоритет</option><option value={1}>TPROXY принудительно</option><option value={2}>REDIRECT · TCP</option></select><label className="block text-xs font-bold opacity-60">DNS</label><select value={Number(config.DNS_HIJACK_ENABLE ?? 1)} onChange={e=>onChange('DNS_HIJACK_ENABLE',Number(e.target.value))} className="w-full rounded-2xl bg-[#f3edf7] px-4 py-3 text-sm dark:bg-[#2b2930]"><option value={1}>Перехват DNS через TPROXY</option><option value={2}>Перехват DNS через REDIRECT</option><option value={0}>Не перехватывать DNS</option></select></div></Card>
    <Card className="overflow-hidden">{[[Wifi,'Wi‑Fi','PROXY_WIFI'],[Smartphone,'Мобильная сеть','PROXY_MOBILE'],[Zap,'UDP','PROXY_UDP'],[ShieldCheck,'Блокировать QUIC','BLOCK_QUIC']].map(([Icon,label,key])=><div key={String(key)} className="flex items-center gap-3 border-b border-black/5 px-4 py-3 last:border-0 dark:border-white/5"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#e8def8] text-[#6750a4] dark:bg-[#4a4458] dark:text-[#e8def8]"><Icon size={19}/></div><div className="flex-1 text-sm font-bold">{String(label)}</div><Toggle value={Number(config[String(key)] ?? (key==='BLOCK_QUIC'?0:1))===1} onChange={v=>onToggle(String(key),v)}/></div>)}</Card>
    <Card className="p-4"><div className="flex items-center justify-between"><div><div className="font-black">Автозапуск</div><div className="text-xs opacity-50">Поднимать прокси после загрузки Android</div></div><Toggle value={Boolean(status.autoStart)} onChange={v=>void onAutoStart(v)}/></div></Card>
    <div className="grid grid-cols-2 gap-2"><button onClick={()=>void onLog()} className="rounded-[22px] bg-[#e8def8] p-3 text-sm font-black text-[#6750a4] dark:bg-[#4a4458] dark:text-[#e8def8]">Диагностика</button><button onClick={()=>void onRestart()} className="rounded-[22px] bg-[#e8def8] p-3 text-sm font-black text-[#6750a4] dark:bg-[#4a4458] dark:text-[#e8def8]">Перезапустить</button></div>
    {hasChanges&&<button disabled={actionLoading==='save'} onClick={()=>void onSave()} className="sticky bottom-4 flex w-full items-center justify-center gap-2 rounded-[24px] bg-[#6750a4] py-4 text-sm font-black text-white shadow-xl">{actionLoading==='save'?<LoaderCircle className="animate-spin" size={18}/>:<Check size={18}/>}Сохранить и применить</button>}
  </div>;
}
